### ISSUE TITLE
Set tax rate in contract constructor

### ISSUE THREAD

**Issue by jannikluhn** [jannikluhn/graffiti#1]
Right now it's hardcoded in `taxRateNominator` and `taxRateDenominator`. The contract constructor should take those two as parameters and set them.

At the moment, tax rate is specified per year. Since time is tracked in seconds, it might or might not make more sense to specify the tax rate in seconds too to avoid conversion and increase accuracy. If we do that, we should update the formulas in `_computeTax` accordingly.

**Comment by herculeeza** [comment]
done
