### ISSUE TITLE
Require minimum deposit

### ISSUE THREAD

**Issue by jannikluhn** [jannikluhn/graffiti#4]
When buying pixels, setting prices, or withdrawing deposit, we should ensure that taxes are covered for at least a certain amount of time (e.g. a month). The time should be configurable, probably in the constructor.

**Comment by herculeeza** [comment]
Theoretically the required deposit could then be used to pay taxes on other pixels, so calculating this gets complicated if the user is already running low on deposit (e.g. already can't afford a month taxes on their pixels). In that case even if we require a deposit, the user could run out earlier.

**Comment by herculeeza** [comment]
Not doing this. The warning will be in the interface instead
