### ISSUE TITLE
Decide if it should be possible to transfer pixels

### ISSUE THREAD

**Issue by jannikluhn** [jannikluhn/graffiti#5]
Transferring pixels is tricky, because you're not only transferring ownership, but also the obligation to pay a tax. At the moment, transferring is simply disabled.

We have to decide if we want to allow it and if so how we implement it.

**Comment by herculeeza** [comment]
Priority: Let users "earmark" a pixel (and a deposit) for another address, and the recipient has to claim it from them.

If time allows: Also let users request pixels at or under a certain price.
(Would be interesting if something like this could transfer a pixel automatically if someone's tax hasn't been paid. But not possible currently without a trigger...)

**Comment by jannikluhn** [comment]
I implemented the earmarking. It's already quite complicated, so I'd suggest to skip the requesting.

To earmark a pixel, you call the `earmark` function and specify the receiver and an amount. The receiver can then call `claim` and will receive the pixel and the amount from the sender's balance (if the balance is too small, the receiver gets the whole balance). The receiver has to specify a maximum pixel price and a minimum amount they'll receive in the function call too, in case they change while the tx is in flight. To cancel an earmark, you earmark it for the zero address.
